Update get-set-up-for-aws-batch.md
awsdocs/aws-batch-user-guide pull request #5
Opened 2018-05-10 18:29 UTC by landermkerbey

Chiefly minor typo fixes. The change to the section about creating an IAM user was about enforcing subject-verb agreement. Depending on intent, it might make more sense to render everything singular, but based on how I read this document, plural made sense. Please advise.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2018-05-10 18:39 UTC, nrdlngr commented
Thanks for your interest in contributing to the AWS Batch User Guide. Looks like that colon should be a semicolon; nice catch. 

I'm not sure I agree with your other rewording suggestions, but if you revert all lines except for the colon-semicolon change, I'll gladly merge this.

2018-05-10 18:52 UTC, landermkerbey commented
@nrdlngr 

What about the 'or and' in the passage titled "Create an IAM User"? If the intent is to say doing both or doing either is appropriate, what about 'and/or'?

Also, what should be done about the subject-verb conflict in the statement 'You must create IAM _roles_ that _provides_ these credentials to your compute environments and container instances and then associate _that_ role with your compute environments'? Do you want that to be singular or plural?

I also noticed that the last paragraph includes the statement 'o use the AWS CLI with AWS Batch, install the latest AWS CLI, version.' Should that be changed to add a specific version number after version, or should I remove the comma?

2018-05-10 19:03 UTC, nrdlngr requested changes
Sorry I misread some of your suggestions on first review. The GitHub diff wasn't flagging some of them so I missed them. I can merge this after you address my comments. Thanks!

2018-05-10 19:03 UTC, nrdlngr commented on doc_source/get-set-up-for-aws-batch.md
> +Your AWS Batch compute environments and container instances require AWS account credentials to make calls to other AWS APIs on your behalf\. You must create IAM roles that provide these credentials t
Sorry, I missed the nuance here on the first look. Apologies. Please make this "create an IAM role" "associate that role".

2018-05-10 19:03 UTC, nrdlngr commented on doc_source/get-set-up-for-aws-batch.md
> +Services in AWS, such as Amazon EC2 and AWS Batch, require that you provide credentials when you access them, so that the service can determine whether you have permission to access its resources\. T
I couldn't see the "and/or" change here before until you called it out in the conversation. You are correct, this should be "or".

2018-05-10 19:03 UTC, nrdlngr commented on doc_source/get-set-up-for-aws-batch.md
> +To use the AWS CLI with AWS Batch, install the latest AWS CLI, version\. For information about installing the AWS CLI or upgrading it to the latest version, see [Installing the AWS Command Line Inter
Please remove the comma in "AWS CLI, version".

2018-05-10 19:11 UTC, landermkerbey commented
Yeah, I noticed that Github was displaying the diffs oddly--for example, in that final paragraph it showed a diff even though I didn't change anything, and it showed the whole paragraph as a diff for that 'or and' thing. I went ahead and made changes reflective of your comments, let me know what you think.

By the way, thanks for being so quick on the draw with the reviews!

2018-05-14 19:21 UTC, nrdlngr commented on doc_source/get-set-up-for-aws-batch.md
> +Your AWS Batch compute environments and container instances require AWS account credentials to make calls to other AWS APIs on your behalf\. You must create an IAM role that provides these credential
Should be "associate that role with".

2018-05-14 19:45 UTC, landermkerbey commented
Woops. Fixed.

2018-06-26 20:04 UTC, merged

2018-06-26 20:05 UTC, nrdlngr commented
Sorry I let this sit idle for so long. Thanks for your contribution!